// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

enum member_role {
  owner
  member
}


Table users {
  id uuid [primary key]
  display_name varchar
  email varchar [unique, not null]
  created_at timestamp [default: `now()`]
}

Table households {
  id uuid [primary key]
  name varchar [not null]
  created_at timestamp [default: `now()`]
}

Table household_members {
  user_id uuid [not null]
  household_id uuid [not null]
  role member_role [not null]
  joined_at timestamp [default: `now()`]
  indexes {
    (user_id, household_id) [pk]
  }
}

Ref: household_members.user_id > users.id [delete: cascade]
Ref: household_members.household_id > households.id [delete: cascade]
